import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  projects: defineTable({
    projectId: v.string(),
    name: v.string(),
    dashboardCodeHash: v.string(),
    dashboardCodeLookup: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
  }).index("by_projectId", ["projectId"]).index("by_dashboardCodeLookup", ["dashboardCodeLookup"]),
  meterKeys: defineTable({
    projectId: v.string(),
    environment: v.union(v.literal("test"), v.literal("live")),
    keyHash: v.string(),
    keyPrefix: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
    rotatedAt: v.optional(v.number()),
  })
    .index("by_project", ["projectId"])
    .index("by_project_environment", ["projectId", "environment"])
    .index("by_project_hash", ["projectId", "keyHash"]),
  eventReceipts: defineTable({
    projectId: v.string(),
    environment: v.union(v.literal("test"), v.literal("live")),
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    state: v.union(v.literal("processing"), v.literal("recorded")),
    attempts: v.number(),
    callId: v.optional(v.id("calls")),
    createdAt: v.number(),
    lastSeenAt: v.number(),
  })
    .index("by_project_environment_key", ["projectId", "environment", "idempotencyKey"])
    .index("by_project_environment_createdAt", ["projectId", "environment", "createdAt"]),
  customers: defineTable({
    projectId: v.string(),
    environment: v.union(v.literal("test"), v.literal("live")),
    customerId: v.string(),
    name: v.optional(v.string()),
    billingEmail: v.optional(v.string()),
    stripeCustomerId: v.optional(v.string()),
    status: v.union(v.literal("active"), v.literal("archived")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_project_environment", ["projectId", "environment"])
    .index("by_project_environment_customer", ["projectId", "environment", "customerId"]),
  rateCards: defineTable({
    projectId: v.string(),
    environment: v.union(v.literal("test"), v.literal("live")),
    provider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini"), v.literal("openrouter")),
    model: v.string(),
    inputUsdPerMillion: v.number(),
    outputUsdPerMillion: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_project_environment", ["projectId", "environment"])
    .index("by_project_environment_provider_model", ["projectId", "environment", "provider", "model"]),
  calls: defineTable({
    projectId: v.string(),
    environment: v.optional(v.union(v.literal("test"), v.literal("live"))),
    idempotencyKey: v.optional(v.string()),
    eventStatus: v.optional(v.union(v.literal("accepted"), v.literal("failed"))),
    pricingStatus: v.optional(v.union(v.literal("priced"), v.literal("unpriced"), v.literal("not_billable"))),
    pricingSource: v.optional(v.union(v.literal("provider"), v.literal("built_in"), v.literal("rate_card"), v.literal("none"))),
    rateCardId: v.optional(v.string()),
    customerId: v.optional(v.string()),
    createdAt: v.number(),
    provider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini"), v.literal("openrouter")),
    providerRequestId: v.optional(v.string()),
    requestedModel: v.string(),
    originalRequestedModel: v.optional(v.string()),
    policyApplied: v.optional(v.boolean()),
    reportedModel: v.optional(v.string()),
    promptTokens: v.number(),
    cachedPromptTokens: v.number(),
    completionTokens: v.number(),
    providerCostUsd: v.optional(v.number()),
    estimatedCostUsd: v.optional(v.number()),
    sameTokenEstimateUsd: v.optional(v.number()),
    costStatus: v.union(v.literal("reported"), v.literal("estimated"), v.literal("unavailable")),
    latencyMs: v.number(),
    status: v.union(v.literal("ok"), v.literal("error")),
    errorCode: v.optional(v.string()),
    trafficType: v.union(v.literal("internal"), v.literal("demo"), v.literal("external")),
    privacyMode: v.optional(v.literal("private")),
    taskId: v.optional(v.string()),
    sessionId: v.optional(v.string()),
    agentName: v.optional(v.string()),
    toolNames: v.optional(v.array(v.string())),
    toolCallCount: v.optional(v.number()),
    qualityScore: v.optional(v.union(v.literal("helpful"), v.literal("not_helpful"))),
    qualityRecordedAt: v.optional(v.number()),
  })
    .index("by_project_createdAt", ["projectId", "createdAt"])
    .index("by_project_environment_createdAt", ["projectId", "environment", "createdAt"])
    .index("by_customerId", ["customerId"]),
  taskPolicies: defineTable({
    projectId: v.string(),
    taskId: v.string(),
    provider: v.optional(v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini"), v.literal("openrouter"))),
    approvedModel: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_project_task", ["projectId", "taskId"]).index("by_project", ["projectId"]),
  billingSettings: defineTable({
    projectId: v.string(),
    mode: v.union(v.literal("percentage"), v.literal("per_thousand_tokens")),
    value: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_project", ["projectId"]),
  pricingRules: defineTable({
    projectId: v.string(),
    environment: v.union(v.literal("test"), v.literal("live")),
    customerId: v.optional(v.string()),
    mode: v.union(v.literal("percentage"), v.literal("per_thousand_tokens")),
    value: v.number(),
    baseAmountUsd: v.number(),
    includedTokens: v.number(),
    version: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_project_environment", ["projectId", "environment"])
    .index("by_project_environment_customer", ["projectId", "environment", "customerId"]),
  billingRuns: defineTable({
    projectId: v.string(),
    environment: v.literal("live"),
    periodStart: v.number(),
    periodEnd: v.number(),
    currency: v.literal("usd"),
    status: v.union(v.literal("closed"), v.literal("exporting"), v.literal("exported"), v.literal("partial")),
    customerCount: v.number(),
    totalAmountCents: v.number(),
    totalRawCostCents: v.number(),
    createdAt: v.number(),
    closedAt: v.number(),
    exportedAt: v.optional(v.number()),
  })
    .index("by_project", ["projectId"])
    .index("by_project_environment_period", ["projectId", "environment", "periodStart", "periodEnd"]),
  billingRunItems: defineTable({
    runId: v.id("billingRuns"),
    projectId: v.string(),
    customerId: v.string(),
    customerName: v.string(),
    billingEmail: v.optional(v.string()),
    stripeCustomerId: v.optional(v.string()),
    sourceCallIds: v.array(v.id("calls")),
    calls: v.number(),
    tokens: v.number(),
    rawCostCents: v.number(),
    unknownCostCalls: v.number(),
    amountCents: v.number(),
    marginCents: v.optional(v.number()),
    rule: v.object({
      mode: v.union(v.literal("percentage"), v.literal("per_thousand_tokens")),
      value: v.number(),
      baseAmountUsd: v.number(),
      includedTokens: v.number(),
      version: v.number(),
    }),
    stripeStatus: v.union(v.literal("not_sent"), v.literal("draft"), v.literal("open"), v.literal("paid"), v.literal("void"), v.literal("failed")),
    stripeInvoiceId: v.optional(v.string()),
    stripeError: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_run", ["runId"])
    .index("by_project_stripe_invoice", ["projectId", "stripeInvoiceId"]),
  stripeConnections: defineTable({
    projectId: v.string(),
    encryptedSecretKey: v.string(),
    encryptedWebhookSecret: v.string(),
    keyPrefix: v.string(),
    accountId: v.string(),
    accountCountry: v.string(),
    livemode: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_project", ["projectId"]),
  stripeWebhookEvents: defineTable({
    projectId: v.string(),
    eventId: v.string(),
    eventType: v.string(),
    stripeInvoiceId: v.string(),
    receivedAt: v.number(),
  }).index("by_project_event", ["projectId", "eventId"]),
  testApplications: defineTable({
    createdAt: v.number(), name: v.string(), email: v.string(), provider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini"), v.literal("openrouter"), v.literal("hosted-open-model"), v.literal("other")), pain: v.optional(v.string()),
    source: v.union(v.literal("growthx"), v.literal("linkedin"), v.literal("direct"), v.literal("other")),
  }).index("by_email", ["email"]),
});
