import type { Metadata } from "next";
import { PublicDocsLayout } from "@/components/public-docs-layout";

export const metadata: Metadata = { title: "Tollgate security and data handling", description: "What Tollgate stores, what passes through memory, and the current private-beta security boundary." };

export default function SecurityPage() {
  return <PublicDocsLayout current="security" eyebrow="Security / Data handling" title="Usage metadata stays. Request content does not." description="The proxy must process provider credentials, prompts, and responses to complete a request. It does not persist them in Tollgate's database.">
    <section className="docs-section"><header><p>01 / Stored</p><h2>Billing evidence only.</h2></header><div className="docs-grid"><article><h3>Usage</h3><ul><li>Project, environment, customer, and retry IDs</li><li>Provider, requested model, reported model, and provider request ID</li><li>Input, cached, and output token counts</li><li>Available cost, price source, latency, and response status</li><li>Safe trace IDs and safe tool names</li></ul></article><article><h3>Billing</h3><ul><li>Customer billing identity and optional Stripe customer ID</li><li>Versioned pricing rules and exact model rate cards</li><li>Fixed billing-run totals and source-call IDs</li><li>Encrypted Stripe restricted key and webhook secret</li></ul></article></div></section>
    <section className="docs-section"><header><p>02 / Excluded</p><h2>Never written to the product database.</h2></header><div className="docs-grid"><article><h3>Provider secrets</h3><p>API keys and authorization headers pass through process memory for the request and are not stored.</p></article><article><h3>Request content</h3><p>Prompts, messages, response bodies, tool arguments, and payloads are not stored.</p></article></div></section>
    <section className="docs-section"><header><p>03 / Controls</p><h2>V1 protection and correctness.</h2></header><ul className="docs-list"><li>Sensitive database functions require a server-only authorization token; direct browser calls are rejected.</li><li>Separate rotatable test and live write keys; only hashes remain after creation.</li><li>A retry ID is reserved before provider spend. A keyed one-way fingerprint covers the prepared request without storing its content, so changed payloads become conflicts.</li><li>Customer IDs are limited to 1–80 safe characters, and provider responses above 4 MiB are rejected.</li><li>Provider origins and request paths are fixed in code; arbitrary upstream URLs are rejected.</li><li>Stripe secrets use AES-256-GCM encryption with project-specific context before storage.</li><li>Stripe webhook signatures are checked against the raw request body.</li><li>Protected dashboard routes use signed, HTTP-only, project-scoped cookies with SameSite Strict; dashboard mutations also require the exact site origin.</li></ul></section>
    <section className="docs-section"><header><p>04 / Observability</p><h2>Traffic and errors without product secrets.</h2></header><div className="docs-grid"><article><h3>Traffic</h3><p>Vercel Web Analytics records basic page traffic. Amplitude can record page views, sessions, web performance, and named activation events when configured.</p></article><article><h3>Blocked data</h3><p>Automatic form, element, file-download, and network capture are disabled. Email addresses, form contents, project IDs, request bodies, prompts, responses, API keys, write keys, recovery codes, cookies, and authorization headers are not sent as analytics properties.</p></article><article><h3>Errors</h3><p>Sentry can receive browser and server errors when configured. Request bodies, headers, cookies, query strings, user data, extra fields, and known secret formats are removed before an error leaves Tollgate.</p></article></div></section>
    <section className="docs-section"><header><p>05 / Current boundary</p><h2>Private beta, not enterprise compliance.</h2></header><p className="docs-note">Tollgate has not completed SOC 2 or an external penetration test. Recovery-code access is for the private beta. Team roles, single sign-on, audit-log export, regional data controls, and formal retention/deletion workflows are not available yet.</p></section>
  </PublicDocsLayout>;
}
