import type { Metadata } from "next";
import { PublicDocsLayout } from "@/components/public-docs-layout";

export const metadata: Metadata = {
  title: "Tollgate privacy notice",
  description: "How Tollgate handles account, usage, billing, analytics, and request data during the private beta.",
};

export default function PrivacyPage() {
  return <PublicDocsLayout current="privacy" eyebrow="Privacy / Effective September 1, 2026" title="A factual record of what Tollgate handles." description="This notice covers the current private beta. It describes the product as it operates today, including the limits that still exist.">
    <section className="docs-section"><header><p>01 / Data provided</p><h2>Account and billing setup.</h2></header><div className="docs-grid"><article><h3>Contact</h3><p>We receive the email address used to create a meter and any name, email, or message submitted through Contact.</p></article><article><h3>Billing identity</h3><p>Customer IDs, display names, billing emails, pricing rules, optional Stripe customer IDs, and fixed billing records are stored for the meter owner.</p></article><article><h3>Access</h3><p>Full recovery codes and write keys are shown once. Tollgate stores hashes used to check them, not the original values.</p></article></div></section>
    <section className="docs-section"><header><p>02 / Model traffic</p><h2>Content passes through but is not persisted.</h2></header><p className="docs-note">Provider credentials, request bodies, prompts, messages, tool arguments, and response bodies pass through process memory only to complete the provider request. Tollgate does not write them to its product database. Usage metadata such as customer ID, provider, model, token counts, available cost, latency, and status is retained.</p></section>
    <section className="docs-section"><header><p>03 / Services</p><h2>Infrastructure needed to operate the beta.</h2></header><div className="docs-grid"><article><h3>Hosting and data</h3><p>Vercel hosts the web application and Convex stores product records. Provider requests are sent to the AI provider selected by the meter owner.</p></article><article><h3>Stripe</h3><p>If connected, Tollgate uses the supplied Stripe restricted key to create draft invoices. The key and webhook secret are encrypted before storage.</p></article><article><h3>Observability</h3><p>Vercel Web Analytics receives basic page traffic without model content. Amplitude and Sentry remain inactive until account keys are configured. Their code is restricted from collecting forms, request bodies, credentials, recovery codes, or model content.</p></article></div></section>
    <section className="docs-section"><header><p>04 / Purpose and control</p><h2>Operate, secure, and improve Tollgate.</h2></header><ul className="docs-list"><li>Provide private meters, usage attribution, pricing, billing runs, exports, and support.</li><li>Prevent duplicate requests, investigate failures, protect access, and maintain service reliability.</li><li>Understand anonymous page traffic and the completion of named product steps.</li><li>Tollgate does not sell personal information or use model content for advertising.</li><li>Dashboard access uses a required HTTP-only session cookie. Amplitude may use browser storage only if it is enabled later.</li></ul></section>
    <section className="docs-section"><header><p>05 / Requests and limits</p><h2>Contact us about your data.</h2></header><p className="docs-note">Formal self-serve deletion and export workflows are not available in this private beta. Use the Contact page to request access, correction, or deletion. We will verify that the requester controls the relevant meter before changing its records. Tollgate is not intended for children.</p></section>
  </PublicDocsLayout>;
}
